[SERVICE]
    flush                    5
    log_level                info
    parsers_file             /etc/fluent-bit/parsers.conf
    plugins_file             /etc/fluent-bit/plugins.conf
    storage.path             /var/log/flb-storage/
    storage.sync             normal
    storage.checksum         on
    storage.backlog.mem_limit 100M
    storage.max_chunks_up    128
    storage.delete_irrecoverable_chunks on
    storage.total_limit_size 2G
    storage.keep.rejected     on
    storage.rejected.path     rejected

[INPUT]
    Name                     tail
    Path                     /var/log/deepflow-agent/l7_flow_log
    Tag                      deepflow.l7
    Parser                   json
    DB                       /var/log/flb-storage/deepflow_l7.db
    Mem_Buf_Limit            200MB
    storage.type             filesystem
    Skip_Long_Lines          On
    Refresh_Interval         2
    Rotate_Wait              5
    Read_from_Head           true

[INPUT]
    Name                     tail
    Path                     /var/log/deepflow-agent/l4_flow_log
    Tag                      deepflow.l4
    Parser                   json
    DB                       /var/log/flb-storage/deepflow_l4.db
    Mem_Buf_Limit            500MB
    storage.type             filesystem
    Skip_Long_Lines          On
    Refresh_Interval         2
    Rotate_Wait              5
    Read_from_Head           true

[INPUT]
    Name                     tail
    Path                     /var/log/deepflow-agent/flow_metrics
    Tag                      deepflow.metrics
    Parser                   json
    DB                       /var/log/flb-storage/deepflow_metrics.db
    Mem_Buf_Limit            200MB
    storage.type             filesystem
    Skip_Long_Lines          On
    Refresh_Interval         2
    Rotate_Wait              5
    Read_from_Head           true

[OUTPUT]
    Name                     deepflow_newrelic
    Match                    deepflow.*
    accountId                123456
    insertKey                ******
    batchSize                200
    flushInterval            5
    logLevel                 info
    httpTimeout              120
    retryLimit               10
