# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: deepflow-secrets
  namespace: css-infra
type: Opaque
stringData:
  NEW_RELIC_ACCOUNT_ID: "2270591"
  NEW_RELIC_LICENSE_KEY: "aa34858ccc90b1145ecff70279c1db02FFFFNRAL"